# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Charley Gaber"                                # Your name
  description: "Assistant Professor at University of Illinois-Chicago"   # A brief slogan (optional)
  image: img/Charles Gaber photograph.jpg
  
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    
    # your sub-pages
    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: twitter
        href: https://twitter.com/CharleyGaber/
      - icon: linkedin
        href: https://www.linkedin.com/in/charles-gaber-phd-mph-4b02bb87/
      - icon: envelope
        aria-label: email
        href: "mailto:gaber1@uic.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
 
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true